Setting improvements
sealink/active_setting pull request #4
Opened 2016-09-16 00:11 UTC by mnoack

Ontop of https://github.com/sealink/active_setting/pull/3

2016-09-16 04:37 UTC, alvinypyim commented
👍

2016-09-16 04:47 UTC, alvinypyim approved these changes

2016-09-20 00:01 UTC, kieronhowland commented on spec/setting_spec.rb
>      end
worth adding a test where the default is a non-empty Array

2016-09-20 00:08 UTC, mnoack commented on spec/setting_spec.rb
>      end
Good point. Test added :)

2016-09-20 00:12 UTC, kieronhowland approved these changes

2016-09-20 00:39 UTC, alxberardi commented
👍 once @kieronhowland 's comment is addressed

2016-09-20 00:40 UTC, alxberardi requested changes
Please address @kieronhowland 's comment about the missing spec

2016-09-20 00:47 UTC, alxberardi approved these changes

2016-09-20 00:47 UTC, merged